- name: 'download and install nginx'
  apt:
    name: nginx
    state: latest
    update_cache: true
- name: 'install config file from template'
  template:
    src: /home/student/nbs-mentored-project/roles/nginx/templates/nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_config
- name: 'start nginx service'
  service:
    name: nginx
    state: started
- name: 'create nginx container'
  community.general.docker_container:
    name: nginx
    image: nginx:alpine
    ports:
      - 81:80
    networks:
      - name: challenge-network
    mounts:
      - type: bind
        source: /home/student/nbs-mentored-project/roles/nginx/templates/nginx.conf
        target: /etc/nginx/nginx.conf
