- name: 'build docker image'
  docker_image:
    name: service-2
    build_path: /home/student/nbs-mentored-project/roles/service-2/files/
    state: present
    tag: latest
- name: 'run service-2 in container'
  docker_container:
    name: service2
    image: service-2:latest
    ports:
      - 5001:5001
    mounts:
      - type: bind
        source: /home/student/nbs-mentored-project/roles/nginx/templates/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - name: challenge-network
    state: started
    
