- name: 'build docker image'
  docker_image:
    name: service-4
    build_path: /home/student/nbs-mentored-project/roles/service-4/files/
    state: present
    tag: latest
- name: 'run service-4 in container'
  docker_container:
    name: service4
    image: service-4:latest
    ports:
      - 5003:5003
    networks:
      - name: challenge-network
    mounts:
      - type: bind
        source: /home/student/nbs-mentored-project/roles/nginx/templates/nginx.conf
        target: /etc/nginx/nginx.conf
    state: started
    
