- name: 'build docker image'
  docker_image:
    name: service-4
    build_path: /home/student/nbs-mentored-project/roles/service-4/files/
    state: present
    tag: latest
- name: 'tag image and push to nexus (with cleanup)'
  script: /home/student/nbs-mentored-project/roles/service-4/files/scripts/push.sh
- name: 'run service-4 in container'
  docker_container:
    name: service-4
    image: service-4:latest
    ports:
      - 5003:5003
    networks:
      - name: challenge-network
    state: started
    
